version: "3.9"

services:
  backend:
    image: nubeeratechnologies/fujitsu-wa-lsa-backend:1.0
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - CLIENT_ORIGIN=http://4.222.217.70:3000

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://4.222.217.70:4000
    depends_on:
      - backend
